'use client';
import { useEffect, useMemo, useState } from 'react';
import { Search, RefreshCw, ChevronDown } from 'lucide-react';
import { api } from '@/lib/api';
import type { Incident, IncidentStatus, Severity } from '@/types/api';
const severities: Severity[]=['CRITICAL','HIGH','MEDIUM','LOW'];
const statuses: IncidentStatus[]=['NEW','INVESTIGATING','CONTAINED','RESOLVED','CLOSED'];
export default function Incidents(){const [items,setItems]=useState<Incident[]>([]),[q,setQ]=useState(''),[sev,setSev]=useState('ALL'),[status,setStatus]=useState('ALL'),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 const load=()=>{setLoading(true);api<Incident[]>('/incidents?limit=100').then(setItems).catch(e=>setError(e.message)).finally(()=>setLoading(false))}; useEffect(load,[]);
 const filtered=useMemo(()=>items.filter(x=>(sev==='ALL'||x.severity===sev)&&(status==='ALL'||x.status===status)&&(`${x.title} ${x.source_ip||''} ${x.destination_ip||''}`.toLowerCase().includes(q.toLowerCase()))),[items,q,sev,status]);
 return <main className="page"><div className="eyebrow">INCIDENT RESPONSE</div><div className="page-header"><div><h1>Incidents</h1><p>Investigate, contain and resolve security incidents.</p></div><button className="refresh" onClick={load}><RefreshCw size={14}/> Refresh</button></div>{error&&<div className="api-warning">{error}</div>}<div className="toolbar"><div className="search"><Search size={15}/><input placeholder="Search incidents, IPs or titles..." value={q} onChange={e=>setQ(e.target.value)}/></div><Select value={sev} onChange={setSev} options={['ALL',...severities]}/><Select value={status} onChange={setStatus} options={['ALL',...statuses]}/></div><div className="panel table-panel"><div className="table-meta"><span>{loading?'Loading…':`${filtered.length} incidents`}</span><span>Authenticated API</span></div><div className="table-scroll"><table><thead><tr><th>Severity</th><th>Incident</th><th>Source → Target</th><th>Status</th><th>Created</th></tr></thead><tbody>{filtered.map(x=><tr key={x.incident_id}><td><span className={`badge ${x.severity.toLowerCase()}`}>{x.severity}</span></td><td><b>{x.title}</b><small>{x.incident_id}</small></td><td className="mono">{x.source_ip||'—'} → {x.destination_ip||'—'}</td><td><span className={`status ${x.status.toLowerCase()}`}>{x.status}</span></td><td className="mono">{new Date(x.created_at).toLocaleString()}</td></tr>)}{!loading&&!filtered.length&&<tr><td colSpan={5}><div className="empty">No incidents match the current filters.</div></td></tr>}</tbody></table></div></div></main>}
function Select({value,onChange,options}:{value:string;onChange:(v:string)=>void;options:string[]}){return <div className="select-wrap"><select value={value} onChange={e=>onChange(e.target.value)}>{options.map(x=><option key={x}>{x}</option>)}</select><ChevronDown size={14}/></div>}
