'use client';
import { useEffect, useMemo, useState } from 'react';
import { Activity, AlertTriangle, ArrowUpRight, CheckCircle2, CircleDot, Clock3, Cpu, ShieldCheck, Target, Wifi } from 'lucide-react';
import { api } from '@/lib/api';
import type { Incident } from '@/types/api';

const fallbackEvents = [
 {time:'—', title:'No live events yet', source:'—', target:'—', level:'LOW'},
];
function ThreatChart({count}:{count:number}){const bars=[34,52,42,68,48,74,61,88,58,46,70,94,72,55,81,67,97,73,62,86,49,78,65,92]; return <div className="chart"><div className="chart-grid"><span>100</span><span>75</span><span>50</span><span>25</span><span>0</span></div><div className="bars">{bars.map((h,i)=><div key={i} className="bar-wrap"><div className="bar" style={{height:`${h}%`}}/><span>{i%4===0?`${String(i/4+1).padStart(2,'0')}:00`:''}</span></div>)}</div></div>}
export default function Dashboard(){
 const [incidents,setIncidents]=useState<Incident[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 useEffect(()=>{api<Incident[]>('/incidents?limit=100').then(setIncidents).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);
 const counts=useMemo(()=>({critical:incidents.filter(x=>x.severity==='CRITICAL').length,active:incidents.filter(x=>!['RESOLVED','CLOSED'].includes(x.status)).length}),[incidents]);
 const events=incidents.slice(0,5).map(x=>({time:new Date(x.created_at).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',second:'2-digit'}),title:x.title,source:x.source_ip||'unknown',target:x.destination_ip||'unknown',level:x.severity}));
 return <main className="page"><header className="page-header"><div><div className="eyebrow">SECURITY OPERATIONS CENTER</div><h1>Command Center</h1><p>Real-time visibility across your protected environment.</p></div><div className="live"><span className="pulse"/> LIVE MONITORING <span className="live-time">API CONNECTED</span></div></header>
 {error&&<div className="api-warning">API unavailable: {error}</div>}
 <section className="stats"><Stat icon={<ShieldCheck/>} label="Security score" value={String(Math.max(0,1000-counts.critical*35-incidents.filter(x=>x.severity==='HIGH').length*12))} suffix="/1000" trend={loading?'Loading':'Live API'} good /><Stat icon={<AlertTriangle/>} label="Critical alerts" value={String(counts.critical).padStart(2,'0')} trend={loading?'Loading':'From incidents'} danger={counts.critical>0}/><Stat icon={<Target/>} label="Active threats" value={String(counts.active)} trend={loading?'Loading':'Open incidents'} good={counts.active===0}/><Stat icon={<Cpu/>} label="Protected endpoints" value="—" trend="Telemetry pending"/></section>
 <section className="grid-main"><div className="panel threat-panel"><div className="panel-head"><div><h2>Threat activity</h2><span>Normalized incident volume</span></div><div className="range"><button className="active">24H</button><button>7D</button><button>30D</button></div></div><ThreatChart count={incidents.length}/><div className="legend"><span><i className="dot critical"/> Critical {counts.critical}</span><span><i className="dot high"/> High {incidents.filter(x=>x.severity==='HIGH').length}</span><span><i className="dot medium"/> Medium {incidents.filter(x=>x.severity==='MEDIUM').length}</span><span><i className="dot low"/> Low {incidents.filter(x=>x.severity==='LOW').length}</span></div></div><div className="panel score-panel"><div className="panel-head"><div><h2>Risk posture</h2><span>Current environment risk</span></div><CircleDot className="muted-icon"/></div><div className="gauge"><div className="gauge-ring"><div><strong>{counts.critical>0?'ELEVATED':'LOW'}</strong><small>{(counts.critical*12.5+counts.active*1.4).toFixed(1)} risk</small></div></div></div><div className="risk-row"><span>Open incidents</span><b>{counts.active}</b></div><div className="risk-row"><span>Critical incidents</span><b>{counts.critical}</b></div></div></section>
 <section className="grid-bottom"><div className="panel events"><div className="panel-head"><div><h2>Live security events</h2><span>Latest detections from the incident API</span></div><a className="ghost" href="/incidents">View all <ArrowUpRight size={15}/></a></div>{(events.length?events:fallbackEvents).map((e,i)=><div className="event" key={e.time+i}><div className={`severity ${e.level.toLowerCase()}`}/><div className="event-main"><b>{e.title}</b><span>{e.source} <em>→</em> {e.target}</span></div><span className={`badge ${e.level.toLowerCase()}`}>{e.level}</span><time>{e.time}</time></div>)}</div><div className="panel sources"><div className="panel-head"><div><h2>Top attack sources</h2><span>Derived from current incidents</span></div></div>{Array.from(incidents.filter(x=>x.source_ip).reduce<Map<string,number>>((m,x)=>m.set(x.source_ip!, (m.get(x.source_ip!)||0)+1),new Map()).entries()).slice(0,5).map(([ip,n])=><div className="source" key={ip}><div className="source-top"><b>{ip}</b><span>Incident source</span><strong>{n}</strong></div><div className="progress"><i style={{width:`${Math.min(100,n*20)}%`}}/></div></div>)}{!incidents.some(x=>x.source_ip)&&<div className="empty">No source IP telemetry in current incidents.</div>}</div></section>
 <section className="footer-strip"><div><Wifi size={16}/><span>API status</span><b className={error?'':'ok'}>{error?'Degraded':'Operational'}</b></div><div><Activity size={16}/><span>Incidents loaded</span><b>{incidents.length}</b></div><div><Clock3 size={16}/><span>Last sync</span><b>{loading?'Syncing…':'Just now'}</b></div><div><CheckCircle2 size={16}/><span>Frontend</span><b className="ok">Ready</b></div></section></main>
}
function Stat({icon,label,value,suffix,trend,good,danger}:{icon:React.ReactNode;label:string;value:string;suffix?:string;trend:string;good?:boolean;danger?:boolean}){return <div className="stat"><div className="stat-icon">{icon}</div><div className="stat-copy"><span>{label}</span><strong>{value}<small>{suffix}</small></strong><em className={danger?'bad':good?'good':''}>{trend}</em></div></div>}
